### ISSUE TITLE
Not compatible with: 1.21.1

### ISSUE THREAD

**Issue by cky008** [Fallen-Breath/litematica-server-paster#8]
### Bug description

Can you update the mod to support 1.21.1 with [Litematica 1.21-0.19.3-sakura.3](https://github.com/sakura-ryoko/litematica/releases/tag/1.21-0.19.3-sakura.3)? Thank you so much!

Error Log(Both on server and client)
```bash
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Litematica Server Paster' (litematica-server-paster) 1.3.1 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'Litematica Server Paster' (litematica-server-paster) 1.3.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Steps to reproduce

add this file to `mods` folder with Minecraft version 1.21.1(Fabric loader 0.16.5) and with Litematica 1.21-0.19.3-sakura.3

### Expected behavior

can work porperly

### Actual behavior

cannot open both the client side and server side

### Relevant logs

Error Log(Both on server and client)
```bash
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Litematica Server Paster' (litematica-server-paster) 1.3.1 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'Litematica Server Paster' (litematica-server-paster) 1.3.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Minecraft version

1.21.1

### Litematica Server Paster version

1.3.1

### Other information

Used mod filename: `litematica-server-paster-mc1.21-v1.3.1.jar`

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
https://github.com/Fallen-Breath/litematica-server-paster/releases/tag/v1.3.2
