### ISSUE TITLE
New Fabric-API ( 0.108.0 ) breaks while connecting to servers

### ISSUE THREAD

**Issue by mattymatty97** [Fallen-Breath/litematica-server-paster#9]
### Bug description

with the new Farbic-API version the game errors out while connecting to a server with the message:
Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'serverbound/minecraft:custom_payload' (litematica-server-paster:network_v2)

### Steps to reproduce

update the fabric-api version to 0.108.0
- try to join a server

### Expected behavior

player connects to the server correctly

### Actual behavior

player disconnects with error message:
Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'serverbound/minecraft:custom_payload' (litematica-server-paster:network_v2)

### Relevant logs

https://pastebin.com/k0EUZTqv

### Minecraft version

1.21.1

### Litematica Server Paster version

1.3.2

### Other information

java exception from logs:
java.lang.ClassCastException: class me.fallenbreath.fanetlib.impl.packet.FanetlibCustomPayload cannot be cast to class net.minecraft.class_8711 (me.fallenbreath.fanetlib.impl.packet.FanetlibCustomPayload and net.minecraft.class_8711 are in unnamed module of loader 'knot' @7fc229ab)

note:
rolling back to the previous Fabric-API version ( 0.107.0 ) works correctly

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
The `fabric-data-attachment-api` from fabric api 0.108.0 loads the `CustomPayloadC2SPacket` earlier than litematica-server-paster registers its network packets, causing the described issue

```
[18:26:18] [Render thread/INFO]: Fanetlib registered 0 c2s packets
[18:26:18] [Render thread/INFO]: [STDERR]: java.lang.Exception: f
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2817.modify$znm000$fanetlib$registerFanetlibPayload_c2s(class_2817.java:1561)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2817.<clinit>(class_2817.java:18)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.mixin.attachment.CustomPayloadS2CPacketAccessor.getMaxPayloadSize(CustomPayloadS2CPacketAccessor.java)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.attachment.sync.AttachmentChange.<clinit>(AttachmentChange.java:57)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.attachment.sync.s2c.AttachmentSyncPayloadS2C.<clinit>(AttachmentSyncPayloadS2C.java:30)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.attachment.sync.AttachmentSync.onInitialize(AttachmentSync.java:101)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:477)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:239)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[18:26:18] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
